appName: actions-runner

runnerImage: quay.io/redhat-github-actions/runner
runnerTag: v1.0.0

githubOwner: ""
githubRepository: ""

# The name of the k8s secret to create.
secretName: "github-pat"
# The name of the key that points to the data within the secret.
# Modify this to store multiple PATs in one secret.
secretKey: "github-pat"
# The PAT itself - must be set if the secret is being created.
githubPat: ""

# Pass labels using array syntax, which is curly braces surrounding comma-separated items.
# --set runnerLabels="{ label1, label2 }" results in the labels "label1" and "label2".
runnerLabels: []

# Adjust replicas depending on your resources available,
# and how many jobs you want to run concurrently.
replicas: 1

# Adjust requests and limits depending on your resources,
# and how heavyweight your workloads are.
memoryRequest: "512Mi"
memoryLimit: "1Gi"
cpuRequest: "100m"
cpuLimit: "250m"

# If you have administrator privileges and understand the security implications of privileged containers,
# set this to true to easily get buildah and podman working, among other things.
# Running as root is still not allowed by the deploy,ent.
privileged: false

# Enable custom cluster PKI loading
# https://docs.openshift.com/container-platform/4.6/networking/configuring-a-custom-pki.html
clusterPKI: false

# You can inject arbitrary environment variables here:
runnerEnv:
    # - name: ENV_VAR
    #   value: env_value
    # or, through the command line:
    # --set runnerEnv[0].name="ENV_VAR" --set runnerEnv[0].value="env_value"

    ## Proxy Configuration Example:
    # - name: https_proxy
    #   value: http://proxy.example.com:9000
    # - name: http_proxy
    #   value: http://proxy.example.com:9000
    # - name: no_proxy
    #   value: localhost
