name: Helm Lint
on:
  push:
  pull_request:

env:
  CHART_DIR: .

jobs:
  helm_lint:
    name: Helm Lint
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - run: helm lint ${{ env.CHART_DIR }}

      - uses: stackrox/kube-linter-action@v1
        with:
          directory: .
          config: kube-linter.config.yml
